M48
; DRILL file {KiCad (6.0.4)} date Fri May 27 00:32:31 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-27T00:32:31-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X272.11Y-90.1
X277.89Y-90.1
X283.697Y-158.885
X283.697Y-164.665
T0
M30
