M48
; DRILL file {KiCad (6.0.4)} date Thu May 26 23:50:21 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-26T23:50:21-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X289.03Y-67.11
X289.03Y-72.89
T2
X23.0Y-23.0
X23.0Y-23.0
X23.0Y-135.0
X24.0Y-246.0
X180.0Y-247.0
X292.0Y-247.0
T0
M30
